Dies und das
shining-man/bsc_display pull request #1
Opened 2024-06-21 07:56 UTC by tueftler0

Ein paar Änderungen

2024-06-30 11:11 UTC, tueftler0 commented on src/display.cpp
> +uint8_t u8_mPowersaveTime = 5;
Ok. Ich hatte diese vor der jetzigen BSC-Mainboard-Implementation erhöht. Nun nicht mehr nötig

2024-06-30 11:20 UTC, tueftler0 commented on README.md
> +PCB >= V2.0: Extension-Port J3 (2x5 pol. Pfostenleiste)<br>
Ok, das würde dann passen.

2024-07-01 04:40 UTC, shining-man requested changes
Den Text in der README ändern, dann sollte es ok sein.

2024-07-01 09:33 UTC, tueftler0 commented
Ja, dann sollte es passen.

2024-07-01 10:44 UTC, tueftler0 commented
Mein Fehler

2024-07-01 21:26 UTC, closed without merging